core-test/src/main/java/org/openstack4j/api/barbican/SecretTests.java, core/src/main/java/org/openstack4j/core/transport/internal/OSBadBooleanDeserializer.java, pom.xml
Replaces https://github.com/openstack4j/openstack4j/pull/1
=> Bump jackson to 2.9.10

.github/release-drafter.yml, .github/workflows/release-management.yml, .gitignore
Once this is merged, changelog will be generated automatically when merge requests are integrated.
=> Introduce release drafter

README.md, core-integration-test/pom.xml
Resolves:
https://github.com/ContainX/openstack4j/pull/1286
https://github.com/ContainX/openstack4j/issues/1284
=> Reformat readme

connectors/okhttp/pom.xml, connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpCommand.java, core/src/main/java/org/openstack4j/core/transport/internal/HttpLoggingFilter.java, core/src/main/java/org/openstack4j/openstack/OSFactory.java
The old implementation was not serving body at all.
=> Improve okhttp wire logging

core-test/src/main/java/org/openstack4j/api/storage/VolumeTypeQuotaTests.java, core-test/src/main/java/org/openstack4j/api/storage/VolumeTypeTests.java, core-test/src/main/resources/storage/v2/updateQuotaSetResponse.json, core/src/main/java/org/openstack4j/model/storage/block/BlockQuotaSet.java, core/src/main/java/org/openstack4j/model/storage/block/builder/BlockQuotaSetBuilder.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderBlockQuotaSet.java
=> Support dynamic volume type quota-sets

core/src/main/java/org/openstack4j/model/storage/object/SwiftHeaders.java, core/src/main/java/org/openstack4j/model/storage/object/options/CreateUpdateContainerOptions.java
=> add X-History-Location header support

core-test/src/main/java/org/openstack4j/api/storage/VolumeTests.java, core-test/src/main/resources/storage/v1/volume.json, core/src/main/java/org/openstack4j/model/storage/block/VolumeAttachment.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeAttachment.java
=> Attachment id getter

core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderBackendStoragePool.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/VolumeBackendPool.java
=> Cinder: Fixed VolumeBackendPool maxoversubscription_ratio type to String

core-test/src/main/java/org/openstack4j/api/network/ListenerV2Tests.java, core-test/src/main/resources/network/listenerv2_default_pool_update.json, core-test/src/main/resources/network/listenerv2_update.json, core/src/main/java/org/openstack4j/model/network/ext/ListenerV2Update.java, core/src/main/java/org/openstack4j/model/network/ext/builder/ListenerV2UpdateBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronListenerV2Update.java
the PR is for issue:
[https://github.com/openstack4j/openstack4j/issues/57](https://github.com/openstack4j/openstack4j/issues/57)
added tests as well.
=> support DefaultPoolId update for LoadBalancer Listener

connectors/resteasy/pom.xml
https://github.com/openstack4j/openstack4j/issues/60
FYI @ylcstarseeker
=> Fix #60: Update resteasy to address security vulnerabilities

.travis.yml
=> travis: Update test container from Trusty to Bionic

connectors/okhttp/pom.xml, connectors/okhttp/src/main/java/org/openstack4j/connectors/okhttp/HttpCommand.java, core/src/main/java/org/openstack4j/core/transport/UntrustedSSL.java
Stop using the deprecated and broken implementation
https://github.com/jenkinsci/openstack-cloud-plugin/issues/303
=> okhttp: Fix insecure SSL invocation on recent JDKs

core/src/main/java/org/openstack4j/api/compute/ComputeService.java, core/src/main/java/org/openstack4j/api/compute/ServerActionsService.java, core/src/main/java/org/openstack4j/model/compute/ServerAction.java, core/src/main/java/org/openstack4j/model/compute/builder/ServerActionEventBuilder.java
Java Docs correction for ServerAction
=> JavaDocs correction for serverAction

core-test/src/main/java/org/openstack4j/api/AbstractTest.java, core-test/src/main/java/org/openstack4j/api/network/NetworkTests.java, core-test/src/main/java/org/openstack4j/api/network/PortTests.java, core-test/src/main/java/org/openstack4j/api/network/SubnetTests.java, core-test/src/main/resources/network/network-external.json, core-test/src/main/resources/network/network.json, core-test/src/main/resources/network/network_zone.json, core-test/src/main/resources/network/networks_filtered.json, core-test/src/main/resources/network/port_external.json, core-test/src/main/resources/network/ports_external.json, core-test/src/main/resources/network/subnet_ipv6.json, core/src/main/java/org/openstack4j/model/common/TimeEntity.java, core/src/main/java/org/openstack4j/model/network/Network.java, core/src/main/java/org/openstack4j/model/network/Port.java, core/src/main/java/org/openstack4j/model/network/Subnet.java, core/src/main/java/org/openstack4j/openstack/murano/v1/domain/MuranoEnvironment.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronNetwork.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java, core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronSubnet.java
=> Fix #89: Neutron: add time fields [network/subnet/port]

core/src/main/java/org/openstack4j/openstack/networking/domain/NeutronPort.java
#92 done.  
I didn't find the conflicting code on the original branch, so I pulled a new branch to merge the problem.
=> use lambda method

core-test/src/main/java/org/openstack4j/api/network/PortForwardingTests.java, core-test/src/main/resources/network/portforwarding/create.json, core-test/src/main/resources/network/portforwarding/get.json, core-test/src/main/resources/network/portforwarding/list.json, core/src/main/java/org/openstack4j/api/Builders.java, core/src/main/java/org/openstack4j/api/networking/NetFloatingIPService.java, core/src/main/java/org/openstack4j/api/networking/ext/PortForwardingService.java, core/src/main/java/org/openstack4j/model/network/builder/NetworkBuilders.java, core/src/main/java/org/openstack4j/model/network/ext/PortForwarding.java, core/src/main/java/org/openstack4j/model/network/ext/builder/PortForwardingBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/builder/NeutronBuilders.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/FloatingIPPortForwarding.java, core/src/main/java/org/openstack4j/openstack/networking/internal/FloatingIPServiceImpl.java, core/src/main/java/org/openstack4j/openstack/networking/internal/ext/PortForwardingServiceImpl.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
https://docs.openstack.org/api-ref/network/v2/#floating-ips-port-forwarding
=> Fix #83: Neutron: Add floatingIp port forwardings service

core-test/src/main/java/org/openstack4j/api/network/NetQosPolicyTests.java, core-test/src/main/resources/network/qos_policies.json, core-test/src/main/resources/network/qos_policy.json, core/src/main/java/org/openstack4j/api/networking/NetworkingService.java, core/src/main/java/org/openstack4j/api/networking/ext/NetQosPolicyService.java, core/src/main/java/org/openstack4j/model/network/ext/NetQosPolicy.java, core/src/main/java/org/openstack4j/model/network/ext/NetQosPolicyUpdate.java, core/src/main/java/org/openstack4j/model/network/ext/builder/NetQosPolicyBuilder.java, core/src/main/java/org/openstack4j/model/network/ext/builder/NetQosPolicyUpdateBuilder.java, core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronNetQosPolicy.java, core/src/main/java/org/openstack4j/openstack/networking/internal/NetworkingServiceImpl.java, core/src/main/java/org/openstack4j/openstack/networking/internal/ext/NetQosPolicyServiceImpl.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
https://docs.openstack.org/api-ref/network/v2/#qos-default-extension
=> Fix #104: Neutron: Add QoS default extension

core/src/main/java/org/openstack4j/api/Apis.java, core/src/main/java/org/openstack4j/api/OSClient.java, core/src/main/java/org/openstack4j/api/placement/PlacementService.java, core/src/main/java/org/openstack4j/api/placement/ext/ResourceProviderService.java, core/src/main/java/org/openstack4j/api/types/ServiceType.java, core/src/main/java/org/openstack4j/model/placement/ext/ProviderInventoriesBody.java, core/src/main/java/org/openstack4j/model/placement/ext/ProviderUsagesBody.java, core/src/main/java/org/openstack4j/model/placement/ext/ResourceProvider.java, core/src/main/java/org/openstack4j/model/placement/ext/ResourceProviderInventories.java, core/src/main/java/org/openstack4j/model/placement/ext/ResourceProviderUsages.java, core/src/main/java/org/openstack4j/openstack/internal/OSClientSession.java, core/src/main/java/org/openstack4j/openstack/placement/domain/ResourceProviderInventoriesBody.java, core/src/main/java/org/openstack4j/openstack/placement/domain/ResourceProviderUsagesBody.java, core/src/main/java/org/openstack4j/openstack/placement/domain/ext/ExtResourceProvider.java, core/src/main/java/org/openstack4j/openstack/placement/domain/ext/ExtResourceProviderInventories.java, core/src/main/java/org/openstack4j/openstack/placement/domain/ext/ExtResourceProviderUsages.java, core/src/main/java/org/openstack4j/openstack/placement/internal/BasePlacementServices.java, core/src/main/java/org/openstack4j/openstack/placement/internal/PlacementServiceImpl.java, core/src/main/java/org/openstack4j/openstack/placement/internal/ext/ResourceProviderServiceImpl.java, core/src/main/java/org/openstack4j/openstack/provider/DefaultAPIProvider.java
Provide support for the new Placement service APIs introduced in Openstack Victoria release.
OpenStack API documentation:
https://docs.openstack.org/api-ref/placement/
Changes ware verified against an OpenStack Victoria instance.
...
Make sure that following is addressed to make the PR easier to process:
=> Placement: Add Victoria Placement Service

README.md
These snippets seem to have an extra unnecessary closing brace
...
Make sure that following is addressed to make the PR easier to process:
=> Remove extra brackets

.github/workflows/ci.yaml
...
Make sure that following is addressed to make the PR easier to process:
=> Add github actions based workflow

LICENSE
Replace custom written LICENSE file with official text of the license. *THIS DOES NOT MODIFY THE LICENSE OF THE PROJECT*. The benefit here is in getting GitHub to recognize the license used.
Make sure that following is addressed to make the PR easier to process:
=> Use actual text of Apache 2 license

core-test/src/main/java/org/openstack4j/api/AbstractTest.java, core-test/src/main/java/org/openstack4j/api/storage/VolumeSnapshotTests.java, core/src/main/java/org/openstack4j/core/transport/internal/HttpExecutor.java, core/src/main/java/org/openstack4j/openstack/storage/block/domain/CinderVolumeSnapshot.java
=> Fix #152 Cinder:create snapshot 'display_description' was unexpected
